//MusicVideo Types

export const GET_MUSIC_VIDEO = "GET_MUSIC_VIDEO";
export const SET_GET_MUSIC_VIDEO_RESPONSE = "SET_GET_MUSIC_VIDEO_RESPONSE";
export const SET_SELECTED_GENRE_ID = "SET_SELECTED_GENRE_ID";
