//MusicVideo Types

export const GET_MUSIC_VIDEO = "GET_MUSIC_VIDEO";
export const SET_GENRE_LIST = "SET_GENRE_LIST";
export const SET_MUSIC_VIDEO_LIST = "SET_MUSIC_VIDEO_LIST";
export const SET_SELECTED_GENRE_ID = "SET_SELECTED_GENRE_ID";
export const SET_VIDEO_LIST = "SET_VIDEO_LIST";
